from scripts import cc_computadora
from scripts import cc_laptop
from scripts import cc_gpu
from scripts import cc_almacenamiento
from scripts import cc_case
from scripts import cc_mb_10
from scripts import cc_mb_11
from scripts import cc_mb_12
from scripts import cc_mb_am4
from scripts import cc_proce_10
from scripts import cc_proce_11
from scripts import cc_proce_12
from scripts import cc_proce_am4
from scripts import cc_psu
from scripts import cc_ram